config/routes.rb
Rails.application.routes.draw do
  root 'pages#homepage'

  get '/signup' => 'users#new', as: 'signup'
  resources :users, only: [:new, :create]

  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  delete '/login' => 'sessions#destroy', as: 'logout'

  resources :users do
    resources :missions
  end
  
  scope :admin do
    resources :users, except: [:new, :create, :destroy, :show]
    post '/:id/set_admin' => 'users#set_admin', as: 'set_admin_user'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :user
  default_scope { order("created_at DESC") }
  validates_presence_of :title, :context, :status, :priority, :start_time, :end_time
  validate :datetime_validate

  STATUS_OPTIONS = [['待處理', 1], ['進行中', 2], ['已完成', 3]]
  PRIORITY_OPTIONS = [['高', 1], ['中', 2], ['低', 3]]

  private
  def datetime_validate
    if start_time > end_time
      errors[:start_time] << '不可大於結束時間'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true, uniqueness: true
  has_many :missions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :authenticate_user!

  def index
    # @missions = Mission.order(sort_column + ' ' + sort_direction)
    # @missions = @missions.where('title LIKE ? OR context LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%").page(params[:page]).per(10)

    # 管理者可看到全部任務
    if current_user.is_admin
      @q = Mission.ransack(params[:q])
      @missions = @q.result.page(params[:page]).per(10)
    else
      @q = current_user.missions.ransack(params[:q])
      @missions = @q.result.page(params[:page]).per(10)
    end
  end

  def new
    @mission = Mission.new
  end
  
  def create
    @mission = current_user.missions.build mission_params

    if @mission.save
      redirect_to user_missions_path(current_user), notice: I18n.t("notice.create_success", name: '任務')
    else
      render :new
    end
  end

  def edit
    @mission = Mission.find_by(id: params[:id])
  end

  def update
    @mission = Mission.find_by(id: params[:id])

    if @mission.update(mission_params)
      redirect_to user_missions_path(current_user), notice: I18n.t("notice.update_success", name: '任務')
    else
      render :edit
    end
  end

  def destroy
    @mission = Mission.find_by(id: params[:id])
    @mission.destroy if @mission
    redirect_to user_missions_path(current_user), notice: I18n.t("notice.delete_success", name: '任務')
  end

  private
  def mission_params
    params.require(:mission).permit(:title, :context, :status, :priority, :start_time, :end_time, :user_id)
  end

  def authenticate_user!
    redirect_to root_path, notice: '請先登入！' unless current_user
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_no_authentication, only: [:new, :create]

  def new

  end

  def create
    user = User.find_by(name: params[:session][:name])

    if user and user.authenticate params[:session][:password]
      # login success
      session[:user_id] = user.id
      flash[:notice] = '登入成功！'
      redirect_to root_path
    else
      flash[:notice] = '帳號或密碼錯誤！'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id) if session[:user_id]
    flash[:notice] = '已登出！'
    redirect_to '/login'
  end

  private
  def require_no_authentication
    redirect_to root_path if current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_admin!, only: [:index, :set_admin, :destroy, :show]

  #=================== admin only ===================
  def index
    @users = User.all.page(params[:page]).per(10)
  end

  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy if @user
    redirect_to users_path, notice: '刪除成功！'
  end

  def set_admin
    @user = User.find_by(id: params[:id])

    if @user.update(is_admin: !@user.is_admin)
      redirect_to users_path, notice: '設定成功！'
    else
      render 'index'
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    @missions = @user.missions.page(params[:page]).per(10)
  end
  #=================== admin only ===================

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:notice] = '註冊成功！'
      redirect_to '/'
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :is_admin)
  end
  
  def authenticate_admin!
    redirect_to root_path, notice: '只有管理員可以使用！' unless current_user.is_admin
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_message_for(obj, name)
    if obj && obj.errors.any?
      result = ''
      obj.errors.full_messages_for(name).each do |message|
        result += '<div class="field_with_errors">'
        result += message 
        result += '</div>'
      end 
    end
    raw result if result.present?
  end

  def hash_text(id, hash)
    text_hash = Hash[hash]
    return text_hash.invert[id]
  end
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if @current_user
      @current_user
    else
      @current_user = User.find_by(id: session[:user_id])
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_footer.html.erb
<div class="container">
  <div class="footer">
    <p>Mission Management</p>
  </div>
</div>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to '任務管理', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "任務列表", user_missions_path(current_user), class: 'nav-link' if current_user %>
      </li>
      <li class="nav-item">
        <%= link_to "新增任務", new_user_mission_path(current_user), class: 'nav-link' if current_user %>
      </li>
    </ul>
    <div class="ml-auto">
        <ul class="navbar-nav">
        <% if current_user %>
          <% if current_user.is_admin %>
            <li class="nav-item">
              <%= link_to "管理帳戶", '/users', class: 'nav-link' %>
            </li>
          <% end %>
          <li class="nav-item">
            哈囉, <%= current_user.name %>  |  <%= link_to '登出', logout_path, method: :delete %>
          </li>
          
        <% else %>
          <%= link_to 'Login', login_path %>  |  <%= link_to 'Sign up', signup_path %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>任務管理 - <%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'navbar' %>
    <% if alert %>
      <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span></button>
        <strong>Warning!</strong><%= alert %>
      </div>
    <% end %>
    <% if notice %>
      <div class="alert alert-info" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span></button>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>

    <%= render 'footer' %>
  </body>
</html>

app/views/missions/_form.html.erb
<%= form_for mission, url: user_mission_path(current_user, mission) do |f| %>
  <div class="form-group">
    <%= f.label :title, t("activerecord.attributes.mission.title") %>
    <%= f.text_field :title, class: 'form-control' %> 
    <%= error_message_for mission, :title %>
    <br />
  </div>

  <div class="form-group">
    <%= f.label :context, t("activerecord.attributes.mission.context") %>
    <%= f.text_area :context, class: 'form-control' %>
    <%= error_message_for mission, :context %>
    <br />
  </div>

  <div class="form-group">
    <%= f.label :priority, t("activerecord.attributes.mission.priority") %>
    <%= f.select(:priority, options_for_select(Mission::PRIORITY_OPTIONS, :selected => mission.priority), { :include_blank => '請選擇' }, class: 'form-control selectpicker') %>
    <%= error_message_for mission, :priority %>
    <br />
  </div>

  <div class="form-group">
    <%= f.label :status, t("activerecord.attributes.mission.status") %>
    <%= f.select(:status, options_for_select(Mission::STATUS_OPTIONS, :selected => mission.status), { :include_blank => '請選擇' }, class: 'form-control selectpicker') %>
    <%= error_message_for mission, :status %>
    <br />
  </div>

  <div class="form-group">
    <%= f.label :start_time, t("activerecord.attributes.mission.start_time") %>
    <%= f.datetime_select :start_time %>
    <%= error_message_for mission, :start_time %>
    <br />
  </div>

  <div class="form-group">
    <%= f.label :end_time, t("activerecord.attributes.mission.end_time") %>
    <%= f.datetime_select :end_time %>
    <%= error_message_for mission, :end_time %>
    <br />
  </div>
  
  <%= f.submit '確認', class: 'btn btn-outline-primary my-2 my-sm-0' %>
<% end %>

app/views/missions/edit.html.erb
<% content_for :title, "更新任務" %>

<div class="container p-3">
  <h2> 更新任務 </h2>
  <%= render 'form', mission: @mission %></div>
</div>

app/views/missions/index.html.erb
<% content_for :title, "任務列表" %>
<div class="container p-3">
  <h2>任務列表</h2>
  <div class="row">
    <div class="col-12">
      <%= search_form_for @q, html: {class: 'search_bar p-4 form-inline'},
                              url: user_missions_path(current_user) do |f| %>
        <div class="px-4">
          <b>搜尋</b>
          <%= f.search_field :title_or_context_cont, placeholder: "search...", class: 'form-control mr-sm-2' %>
        </div>

        <div class="px-4">
          <b>狀態</b>
          <%= f.select :status_eq, Mission::STATUS_OPTIONS , { :include_blank => '請選擇' }, class: 'form-control selectpicker' %>
        </div>

        <div class="ml-auto px-5">
          <%= f.submit '搜尋', class: 'btn btn-outline-success my-2 my-sm-0' %>
        </div>
      <% end %>
    </div>
  </div>
  
  <%= sort_link @q, :priority, '依優先權排序', html: {class: 'badge badge-pill badge-info'} %>
  <%= sort_link @q, :end_time, '依結束時間排序', html: {class: 'badge badge-pill badge-info'}  %>
</div>

<div class="container">

  <table class="table">
    <thead>
      <tr>
        <th> 編號 </th>
        <th> <%= t("activerecord.attributes.mission.title") %> </th>
        <th> <%= t("activerecord.attributes.mission.context") %> </th>
        <th> <%= t("activerecord.attributes.mission.status") %> </th>
        <th> <%= t("activerecord.attributes.mission.priority") %> </th>
        <th> <%= t("activerecord.attributes.mission.start_time") %> </th>
        <th> <%= t("activerecord.attributes.mission.end_time") %> </th>
        <th> <%= t("activerecord.attributes.mission.create_user") %> </th>
        <th> 動作 </th>
      </tr>
    </thead>
    <tbody>
      <% @missions.each do |mission| %>
      <tr>
        <td> <%= mission.id %> </td>
        <td> <%= truncate mission.title, length: 15 %> </td>
        <td> <%= truncate mission.context, length: 15 %> </td>
        <td> <%= hash_text mission.status, Mission::STATUS_OPTIONS %> </td>
        <td> <%= hash_text mission.priority, Mission::PRIORITY_OPTIONS %> </td>
        <td> <%= mission.start_time.strftime('%Y-%m-%d %H:%M:%S') if mission.start_time %> </td>
        <td> <%= mission.end_time.strftime('%Y-%m-%d %H:%M:%S') if mission.end_time %> </td>
        <td> <%= mission.user.name if mission.user %> </td>
        <td>
            <%= link_to "編輯", edit_user_mission_path(current_user, mission), class: 'btn btn-outline-success my-2 my-sm-0' %>
            <%= link_to "刪除", user_missions_path(current_user, mission), method: "delete", data: { confirm: "確認刪除？" }, class: 'btn btn-outline-danger my-2 my-sm-0' %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <br>
</div>
<div class="container pagination">
  <%= paginate @missions %>
</div>
<br>

app/views/missions/new.html.erb
<% content_for :title, "新增任務" %>
<div class="container p-3">
  <h2> 新增任務 </h2>


  <%= form_for @mission, url: user_missions_path(current_user, @mission) do |f| %>
    <div class="form-group">
      <%= f.label :title, t("activerecord.attributes.mission.title") %>
      <%= f.text_field :title, class: 'form-control' %> 
      <%= error_message_for @mission, :title %>
      <br />
    </div>

    <div class="form-group">
      <%= f.label :context, t("activerecord.attributes.mission.context") %>
      <%= f.text_area :context, class: 'form-control' %>
      <%= error_message_for @mission, :context %>
      <br />
    </div>

    <div class="form-group">
      <%= f.label :priority, t("activerecord.attributes.mission.priority") %>
      <%= f.select(:priority, options_for_select(Mission::PRIORITY_OPTIONS, :selected => @mission.priority), { :include_blank => '請選擇' }, class: 'form-control selectpicker') %>
      <%= error_message_for @mission, :priority %>
      <br />
    </div>

    <div class="form-group">
      <%= f.label :status, t("activerecord.attributes.mission.status") %>
      <%= f.select(:status, options_for_select(Mission::STATUS_OPTIONS, :selected => @mission.status), { :include_blank => '請選擇' }, class: 'form-control selectpicker') %>
      <%= error_message_for @mission, :status %>
      <br />
    </div>

    <div class="form-group">
      <%= f.label :start_time, t("activerecord.attributes.mission.start_time") %>
      <%= f.datetime_select :start_time %>
      <%= error_message_for @mission, :start_time %>
      <br />
    </div>

    <div class="form-group">
      <%= f.label :end_time, t("activerecord.attributes.mission.end_time") %>
      <%= f.datetime_select :end_time %>
      <%= error_message_for @mission, :end_time %>
      <br />
    </div>
    
    <%= f.submit '確認', class: 'btn btn-outline-primary my-2 my-sm-0' %>
  <% end %>

</div>

app/views/pages/homepage.html.erb
<% content_for :title, "首頁" %>

<div class="container">
　　<div class="row">
　　　<div class="col-md-12">
　　　　<h2>
　　　　　Welcome to Mission Management （任務管理系統）
　　　　</h2>
　　　　<p>
　　　　　　Hi there, This is a Missions Management system that helps you accurately manage the project's timeline to ensure that the project is successfully achieved.
　　　　</p>
       <% if !current_user %>
  　　　　<p>
          You must login first to use... 
          <%= link_to 'Login here >>', login_path %>
  　　　　</p>
        <% end %>
　　　</div>
　　</div>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<% content_for :title, "後台使用者管理" %>
<div class="container p-3">
  <h2>後台使用者管理</h2>
</div>

<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th> 編號 </th>
        <th> 名稱 </th>
        <th> 是否為管理者 </th>
        <th> 任務數量 </th>
        <th> 建立時間 </th>
        <th> 更新時間 </th>
        <th> 動作 </th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td> <%= user.id %> </td>
        <td> <%= link_to user.name, user_path(user) %> </td>
        <td> <%= user.is_admin ? "是" : "否" %> </td>
        <td> <%= user.missions.count %> </td>
        <td> <%= user.created_at.strftime('%Y-%m-%d %H:%M:%S') if user.created_at %> </td>
        <td> <%= user.updated_at.strftime('%Y-%m-%d %H:%M:%S') if user.updated_at %> </td>
        <td>
            <% if current_user.id != user.id %>
              <%= link_to "設定管理者", set_admin_user_path(user), method: "post", data: { confirm: "確認設定[#{user.name}]管理者？" } , class: 'btn btn-outline-success my-2 my-sm-0' %>
              <%= link_to "刪除", user_path(user), method: "delete", data: { confirm: "確認刪除？" }, class: 'btn btn-outline-danger my-2 my-sm-0' %>
            <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <br>
</div>
<div class="container pagination">
  <%= paginate @users %>
</div>
<br>

app/views/users/new.html.erb
<% content_for :title, "註冊新用戶" %>
<div class="container">
  <div class="row">
    <div class="col-2"></div>
      <div class="col-8">
        <%= form_for @user, html: {class: 'form-signin'} do |f| %>
          <img class="mb-4" src="/docs/4.3/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
          <h1 class="h3 mb-3 font-weight-normal">歡迎！現在開始註冊新用戶</h1>
          <div class="form-group">
            <%= f.label :name, class: 'sr-only' %>
            <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
            <%= error_message_for @user, :name %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'sr-only' %>
            <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
            <%= error_message_for @user, :password %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'sr-only' %>
            <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Password confirmation' %>
            <%= error_message_for @user, :password_confirmation %>
          </div>

          <%= f.submit '註冊', class: 'btn btn-primary btn-block' %>
        <% end %>
      </div>
    <div class="col-2"></div>
  </div>
</div>

app/views/users/show.html.erb
<% content_for :title, "任務列表" %>

<div class="container">

  <table class="table">
    <thead>
      <tr>
        <th> 編號 </th>
        <th> <%= t("activerecord.attributes.mission.title") %> </th>
        <th> <%= t("activerecord.attributes.mission.context") %> </th>
        <th> <%= t("activerecord.attributes.mission.status") %> </th>
        <th> <%= t("activerecord.attributes.mission.priority") %> </th>
        <th> <%= t("activerecord.attributes.mission.start_time") %> </th>
        <th> <%= t("activerecord.attributes.mission.end_time") %> </th>
        <th> <%= t("activerecord.attributes.mission.create_user") %> </th>
        <th> 動作 </th>
      </tr>
    </thead>
    <tbody>
      <% @missions.each do |mission| %>
      <tr>
        <td> <%= mission.id %> </td>
        <td> <%= truncate mission.title, length: 15 %> </td>
        <td> <%= truncate mission.context, length: 15 %> </td>
        <td> <%= hash_text mission.status, Mission::STATUS_OPTIONS %> </td>
        <td> <%= hash_text mission.priority, Mission::PRIORITY_OPTIONS %> </td>
        <td> <%= mission.start_time.strftime('%Y-%m-%d %H:%M:%S') if mission.start_time %> </td>
        <td> <%= mission.end_time.strftime('%Y-%m-%d %H:%M:%S') if mission.end_time %> </td>
        <td> <%= mission.user.name if mission.user %> </td>
        <td>
            <%= link_to "編輯", edit_user_mission_path(current_user, mission), class: 'btn btn-outline-success my-2 my-sm-0' %>
            <%= link_to "刪除", user_missions_path(current_user, mission), method: "delete", data: { confirm: "確認刪除？" }, class: 'btn btn-outline-danger my-2 my-sm-0' %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <br>
</div>
<div class="container pagination">
  <%= paginate @missions %>
</div>
<br>